sudo: false
notifications:
  email:
    recipients:
      - freefony@gmail.com
    on_success: change
    on_failure: change
language: node_js
node_js:
  - '4.0'
  - '0.10'

before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - bower install
  - gulp build
after_success:
  - npm run coveralls
